version: '3.8'
services:
  db:
    image: postgres:13.1
    container_name: postgresql13
    environment:
      POSTGRES_USER: momock
      POSTGRES_PASSWORD: momock
    ports:
      - '5432:5432'
    networks:
      - momock_network
    volumes:
      # mount 的方式，可以通过git进行同步，适合团队使用
      - ./db_data:/var/lib/postgresql/data
      # volume 的方式可以避免git污染,适合个人使用
      # - db-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@momock.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8889:80'
    networks:
      - momock_network
    links:
      - 'db:db'

networks:
  momock_network:
    driver: bridge
# 创建一个本地卷 用于持续化数据
volumes:
  db-data:
