version: '3.8'
services:
  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: momock
      POSTGRES_PASSWORD: momock
    ports:
      - '5432:5432'
    networks:
      - momock_network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@momock.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8889:80'
    networks:
      - momock_network

networks:
  momock_network:
    driver: bridge

volumes:
  db-data:
